### ISSUE TITLE
Error type assertion gives 2 options as optional

### ISSUE THREAD

**Issue by PXshadow** [PXshadow/go2hx#15]
I'm not quite sure how this works it seems to be equivlant to ``value,ok := map[get]`` where there is the value and then an optional, bool.

Here is the code example: 

```go
type argError struct {
    arg  int
    prob string
}
func f2(arg int) (int, error) {
	if arg == 42 {

		// In this case we use `&argError` syntax to build
		// a new struct, supplying values for the two
		// fields `arg` and `prob`.
		return -1, &argError{arg, "can't work with it"}
	}
	return arg + 3, nil
}


func (e *argError) Error() string {    
 return fmt.Sprintf("%d - %s", e.arg, e.prob)
}


func main() {
    _, e := f2(42)
    if ae, ok := e.(*argError); ok {
        fmt.Println(ae.arg)
        fmt.Println(ae.prob)
    }
}
``` 

Need to figure out some method to handle this as there is only the option for one variable or multiple variables but they all must be captured with a destruct.

**Comment by elliott5** [comment]
Not sure it matters in this example, but in Go, to be an "error", a type must have a method `Error()` that returns `string`. So in the code above, `argError` is not a Go error type because it does not conform to the `Error` interface. See https://blog.golang.org/error-handling-and-go.

Returning multiple values is quite normal in Go, using their positions to name them. Indeed assignments can have multiple values too. Some examples are at https://riptutorial.com/go/example/2193/multiple-variable-assignment.

My recollection is that TardisGo used Haxe anonymous structures to return multiple values, with names "r0","r1","r2"... to give the positional information.

In hx2go's AST->AST conversion, that is more complicated for one of the above examples, where `a` and `b` would need to be remapped to `r0` and `r1` in the Haxe anonymous structure to be returned:
```
func multipleReturn2() (a int, b int) {
    a = 3
    b = 4
    return
}
```

And yes, the Haxe code generated requires the returned anonymous structure to be put into a temporary variable and then the individual return values taken out of it.

**Comment by PXshadow** [comment]
Apologies, I updated the code snippet I left out the receiver function (the code comes from gobyexamples's Errors) . I currently have a system for anonymous variable names with positions at the end, and not yet for named variables. You bring up a good idea to create temporary variables at the start of the function expr if the return values are named, and then return them through an anonymous structure. Thank you for the info and I'll go through the Go's blog post on Errors that should be quite useful.

**Comment by PXshadow** [comment]
This seems to be working fine for the latest few test cases I've stumbled upon this, and future new cases can be setup accordingly.
